"""Convert curated public live telemetry into bounded fresh headless training pressure.

This module closes the safe early live-experience loop without treating recorded live trajectories as
on-policy PPO data. An operator first approves public telemetry and materializes an immutable
scenario-mining selection. The selection can then be registered as a reviewed matchup/geometry
pressure artifact. At launch time every underlying approval/archive is revalidated; revocation or
tampering disables the derived pressure. Unity receives only a matchup and optional geometry, so
all PPO experience remains freshly generated by the current training policy.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Mapping, Optional, Sequence, Tuple

from bees_continual_adversarial import (
    MAX_TOTAL_TARGET_FRACTION,
    _parse_composition,
    _parse_tactical_geometry,
    _target_fraction,
    _tactical_geometry,
)
from bees_continual_learning import (
    ContinualLearningError,
    ContinualLearningStore,
    ValidationError,
    canonical_json,
    load_config,
    sha256_bytes,
    sha256_file,
    utc_now,
)
from bees_continual_telemetry_curation import (
    PUBLIC_TELEMETRY_SELECTION_SCHEMA_VERSION,
    _approved_archive,
    _read_json_object,
)


TELEMETRY_PRESSURE_SCHEMA_VERSION = 1
_SELECTION_ID = re.compile(r"^telemetry-selection-[0-9a-f]{24}$")
_SCENARIO_ID = re.compile(r"^telemetry-adv-[0-9a-f]{24}$")


def _selection_path(store: ContinualLearningStore, selection_id: str) -> Path:
    return (
        store.experience_dir
        / "raw-live"
        / "public-scenario-selections"
        / selection_id
        / "manifest.json"
    )


def _validated_selection(
    store: ContinualLearningStore,
    selection_id: str,
) -> Mapping[str, object]:
    if not isinstance(selection_id, str) or not _SELECTION_ID.fullmatch(selection_id):
        raise ValidationError(f"Invalid public telemetry selection ID: {selection_id!r}.")
    path = _selection_path(store, selection_id)
    manifest = _read_json_object(path, "Public telemetry scenario selection")
    if manifest.get("schema_version") != PUBLIC_TELEMETRY_SELECTION_SCHEMA_VERSION:
        raise ValidationError(f"Telemetry selection schema is incompatible: {selection_id}.")
    if manifest.get("selection_id") != selection_id:
        raise ValidationError(f"Telemetry selection identity mismatch: {selection_id}.")
    if manifest.get("purpose") != "offline-scenario-mining":
        raise ValidationError(f"Telemetry selection has the wrong purpose: {selection_id}.")
    if manifest.get("approved_for_on_policy_rl") is not False:
        raise ValidationError(
            f"Telemetry selection {selection_id} must remain prohibited from direct on-policy RL use."
        )

    batches = manifest.get("batches")
    if not isinstance(batches, list) or not batches:
        raise ValidationError(f"Telemetry selection contains no approved batches: {selection_id}.")

    expected_batches = []
    seen = set()
    for entry in batches:
        if not isinstance(entry, Mapping):
            raise ValidationError(f"Telemetry selection has malformed batch provenance: {selection_id}.")
        batch_id = entry.get("batch_id")
        if not isinstance(batch_id, str) or batch_id in seen:
            raise ValidationError(f"Telemetry selection has invalid/duplicate batch identity: {selection_id}.")
        seen.add(batch_id)
        archive = _approved_archive(store, batch_id)
        expected = {
            "batch_id": batch_id,
            "match_id": archive["row"]["match_id"],
            "model_id": archive["row"]["model_id"],
            "payload_sha256": archive["payload_sha256"],
            "approval_sha256": sha256_file(archive["approval_path"]),
            "tags": list(archive["approval"].get("tags", [])),
        }
        if dict(entry) != expected:
            raise ValidationError(
                f"Telemetry selection {selection_id} no longer matches approved batch {batch_id}."
            )
        expected_batches.append(expected)

    if [entry["batch_id"] for entry in expected_batches] != sorted(seen):
        raise ValidationError(f"Telemetry selection batch ordering is non-canonical: {selection_id}.")

    identity = {
        "schema_version": PUBLIC_TELEMETRY_SELECTION_SCHEMA_VERSION,
        "purpose": "offline-scenario-mining",
        "approved_for_on_policy_rl": False,
        "batches": expected_batches,
    }
    selection_hash = sha256_bytes(canonical_json(identity).encode("utf-8"))
    if selection_id != f"telemetry-selection-{selection_hash[:24]}":
        raise ValidationError(f"Telemetry selection content hash mismatch: {selection_id}.")
    return {"manifest": manifest, "path": path, "identity_sha256": selection_hash}


def _scenario_path(store: ContinualLearningStore, scenario_id: str) -> Path:
    return (
        store.experience_dir
        / "raw-live"
        / "public-scenario-pressure"
        / f"{scenario_id}.json"
    )


def register_telemetry_pressure(
    store: ContinualLearningStore,
    selection_id: str,
    *,
    bee_composition: Sequence[str] | str,
    human_composition: Sequence[str] | str,
    target_fraction: float,
    rationale: str,
    map_size: Optional[float] = None,
    spawn_separation_ratio: Optional[float] = None,
) -> Mapping[str, object]:
    """Register reviewed live telemetry as scenario pressure, never as PPO trajectory data."""
    store._require_initialized()
    selection = _validated_selection(store, selection_id)
    bees = _parse_composition(bee_composition, "bee_composition")
    humans = _parse_composition(human_composition, "human_composition")
    if len(bees) != len(humans):
        raise ValidationError("Bee and Human telemetry-derived compositions must have equal team size.")
    fraction = _target_fraction(target_fraction)
    if fraction > MAX_TOTAL_TARGET_FRACTION:
        raise ValidationError(
            f"Telemetry-derived pressure cannot exceed {MAX_TOTAL_TARGET_FRACTION:g} of episodes."
        )
    if not isinstance(rationale, str) or not rationale.strip() or len(rationale.strip()) > 2048:
        raise ValidationError("rationale must be a non-empty string up to 2048 characters.")
    geometry = _tactical_geometry(map_size, spawn_separation_ratio)

    identity = {
        "schema_version": TELEMETRY_PRESSURE_SCHEMA_VERSION,
        "source": "approved-public-live-telemetry-selection",
        "selection_id": selection_id,
        "selection_identity_sha256": selection["identity_sha256"],
        "policy_abi_version": store.compatibility.policy_abi_version,
        "bee_composition": list(bees),
        "human_composition": list(humans),
        "target_fraction": fraction,
        "rationale": rationale.strip(),
        "fresh_on_policy_rollouts_required": True,
        "recorded_actions_used_as_ppo_trajectories": False,
    }
    if geometry is not None:
        identity["geometry"] = geometry
    identity_hash = sha256_bytes(canonical_json(identity).encode("utf-8"))
    scenario_id = f"telemetry-adv-{identity_hash[:24]}"
    path = _scenario_path(store, scenario_id)
    body = {
        "schema_version": TELEMETRY_PRESSURE_SCHEMA_VERSION,
        "scenario_id": scenario_id,
        "identity_sha256": identity_hash,
        "identity": identity,
        "created_at": utc_now(),
    }
    if path.exists():
        existing = _read_json_object(path, "Telemetry-derived pressure")
        if existing.get("identity_sha256") == identity_hash and existing.get("identity") == identity:
            return {"scenario_id": scenario_id, "duplicate": True, "path": str(path), "scenario": existing}
        raise ContinualLearningError(f"Refusing to overwrite different telemetry pressure: {path}")
    ContinualLearningStore._write_json_immutable(path, body)
    return {"scenario_id": scenario_id, "duplicate": False, "path": str(path), "scenario": body}


def _validated_scenario(
    store: ContinualLearningStore,
    scenario_id: str,
) -> Mapping[str, object]:
    if not isinstance(scenario_id, str) or not _SCENARIO_ID.fullmatch(scenario_id):
        raise ValidationError(f"Invalid telemetry-derived scenario ID: {scenario_id!r}.")
    path = _scenario_path(store, scenario_id)
    body = _read_json_object(path, "Telemetry-derived pressure")
    if body.get("schema_version") != TELEMETRY_PRESSURE_SCHEMA_VERSION or body.get("scenario_id") != scenario_id:
        raise ValidationError(f"Telemetry-derived pressure identity is incompatible: {scenario_id}.")
    identity = body.get("identity")
    if not isinstance(identity, Mapping):
        raise ValidationError(f"Telemetry-derived pressure identity is missing: {scenario_id}.")
    identity_hash = sha256_bytes(canonical_json(dict(identity)).encode("utf-8"))
    if body.get("identity_sha256") != identity_hash or scenario_id != f"telemetry-adv-{identity_hash[:24]}":
        raise ValidationError(f"Telemetry-derived pressure hash mismatch: {scenario_id}.")
    if identity.get("policy_abi_version") != store.compatibility.policy_abi_version:
        raise ValidationError(f"Telemetry-derived pressure targets a different policy ABI: {scenario_id}.")
    if identity.get("fresh_on_policy_rollouts_required") is not True or identity.get("recorded_actions_used_as_ppo_trajectories") is not False:
        raise ValidationError(f"Telemetry-derived pressure violates the on-policy safety contract: {scenario_id}.")
    selection = _validated_selection(store, str(identity.get("selection_id", "")))
    if identity.get("selection_identity_sha256") != selection["identity_sha256"]:
        raise ValidationError(f"Telemetry-derived pressure selection identity changed: {scenario_id}.")
    _parse_tactical_geometry(identity.get("geometry"))
    return body


def encode_telemetry_pressure_for_unity(
    store: ContinualLearningStore,
    scenario_ids: Sequence[str],
) -> Tuple[str, str]:
    """Encode reviewed telemetry pressure into fresh-rollout Unity matchup/geometry arguments."""
    store._require_initialized()
    if not scenario_ids:
        raise ValidationError("At least one telemetry-derived scenario must be selected.")
    normalized = sorted(set(scenario_ids))
    if len(normalized) != len(scenario_ids):
        raise ValidationError("Telemetry-derived scenario selection contains duplicate IDs.")

    encoded = []
    geometry_encoded = []
    expected_ship_count = None
    total_fraction = 0.0
    for scenario_id in normalized:
        scenario = _validated_scenario(store, scenario_id)
        identity = scenario["identity"]
        bees = _parse_composition(identity.get("bee_composition"), "bee_composition")
        humans = _parse_composition(identity.get("human_composition"), "human_composition")
        if len(bees) != len(humans):
            raise ValidationError(f"Telemetry-derived scenario has asymmetric team sizes: {scenario_id}.")
        if expected_ship_count is None:
            expected_ship_count = len(bees)
        elif len(bees) != expected_ship_count:
            raise ValidationError("Selected telemetry-derived scenarios must use one common ships-per-side value.")
        fraction = _target_fraction(identity.get("target_fraction"))
        total_fraction += fraction
        encoded.append(f"{scenario_id}:{','.join(bees)}>{','.join(humans)}@{fraction:g}")
        geometry = _parse_tactical_geometry(identity.get("geometry"))
        if geometry is not None:
            geometry_encoded.append(
                f"{scenario_id}:{float(geometry['map_size']):g},{float(geometry['spawn_separation_ratio']):g}"
            )
    if total_fraction > MAX_TOTAL_TARGET_FRACTION + 1e-12:
        raise ValidationError(
            f"Selected telemetry-derived scenarios request {total_fraction:.3f} of episodes; "
            f"the combined maximum is {MAX_TOTAL_TARGET_FRACTION:.3f}."
        )
    return ";".join(encoded), ";".join(geometry_encoded)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert approved public live telemetry selections into fresh headless training pressure."
    )
    parser.add_argument("--root", required=True)
    parser.add_argument("--config", default=None)
    sub = parser.add_subparsers(dest="command", required=True)

    register = sub.add_parser("register")
    register.add_argument("selection_id")
    register.add_argument("--bee-composition", required=True)
    register.add_argument("--human-composition", required=True)
    register.add_argument("--target-fraction", required=True, type=float)
    register.add_argument("--rationale", required=True)
    register.add_argument("--map-size", type=float)
    register.add_argument("--spawn-separation-ratio", type=float)

    encode = sub.add_parser("encode")
    encode.add_argument("scenario_ids", nargs="+")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _parser().parse_args(argv)
    try:
        store = ContinualLearningStore(args.root, load_config(args.config))
        if args.command == "register":
            result = register_telemetry_pressure(
                store,
                args.selection_id,
                bee_composition=args.bee_composition,
                human_composition=args.human_composition,
                target_fraction=args.target_fraction,
                rationale=args.rationale,
                map_size=args.map_size,
                spawn_separation_ratio=args.spawn_separation_ratio,
            )
            print(json.dumps(result, indent=2, sort_keys=True))
        else:
            matchup, geometry = encode_telemetry_pressure_for_unity(store, args.scenario_ids)
            print(json.dumps({"matchups": matchup, "geometry": geometry}, indent=2, sort_keys=True))
        return 0
    except ContinualLearningError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
