"""Native ML-Agents distributed rollout support for Bees.

The central Python process remains the only PPO learner and optimizer owner. A configurable suffix
of ML-Agents worker IDs is marked external: those worker subprocesses open the normal ML-Agents gRPC
endpoint but do not launch a local Unity executable. Remote machines connect through loopback-only
SSH forwards and therefore participate in the exact same on-policy SubprocessEnvManager as local
environments.

External workers are pinned to a content-hashed session spec generated by the central launcher. The
spec carries the exact worker IDs, base port, run ID and Unity ``--env-args`` so remote machines cannot
silently train a different scenario distribution because ML-Agents itself does not transmit command-
line environment arguments over its communicator.

This module deliberately does not define a custom trajectory format, average networks, or allow
remote machines to own optimizer/checkpoint state.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, List, Mapping, Optional, Sequence, Tuple


EXPECTED_MLAGENTS_VERSION = "1.1.0"
EXTERNAL_ENVS_FLAG = "--bees-external-envs"
REMOTE_SPEC_FLAG = "--bees-remote-spec"
REMOTE_SPEC_SCHEMA_VERSION = 1
DEFAULT_NUM_ENVS = 1
DEFAULT_BASE_PORT = 5005


@dataclass(frozen=True)
class DistributedOptions:
    external_envs: int = 0
    remote_spec: Optional[str] = None

    @property
    def enabled(self) -> bool:
        return self.external_envs > 0


def _positive_or_zero_integer(value: str, flag: str) -> int:
    try:
        parsed = int(value)
    except ValueError as exc:
        raise SystemExit(f"{flag} requires a whole number; got {value!r}.") from exc
    if parsed < 0:
        raise SystemExit(f"{flag} requires a non-negative whole number; got {value!r}.")
    return parsed


def _read_value(argv: Sequence[str], index: int, flag: str) -> Tuple[Optional[str], int]:
    argument = argv[index]
    if argument == flag:
        if index + 1 >= len(argv) or argv[index + 1].startswith("--"):
            raise SystemExit(f"{flag} requires a value.")
        return argv[index + 1], index + 2
    prefix = flag + "="
    if argument.startswith(prefix):
        value = argument[len(prefix) :]
        if not value:
            raise SystemExit(f"{flag} requires a value.")
        return value, index + 1
    return None, index


def extract_distributed_options(argv: Sequence[str]) -> Tuple[List[str], DistributedOptions]:
    cleaned: List[str] = []
    external_envs: Optional[int] = None
    remote_spec: Optional[str] = None
    index = 0
    while index < len(argv):
        value, next_index = _read_value(argv, index, EXTERNAL_ENVS_FLAG)
        if value is not None:
            if external_envs is not None:
                raise SystemExit(f"{EXTERNAL_ENVS_FLAG} may be specified only once.")
            external_envs = _positive_or_zero_integer(value, EXTERNAL_ENVS_FLAG)
            index = next_index
            continue

        value, next_index = _read_value(argv, index, REMOTE_SPEC_FLAG)
        if value is not None:
            if remote_spec is not None:
                raise SystemExit(f"{REMOTE_SPEC_FLAG} may be specified only once.")
            remote_spec = value
            index = next_index
            continue

        cleaned.append(argv[index])
        index += 1

    normalized_external = external_envs or 0
    if normalized_external > 0 and not remote_spec:
        raise SystemExit(
            f"{REMOTE_SPEC_FLAG} is required when {EXTERNAL_ENVS_FLAG} is greater than zero. "
            "The session spec pins remote Unity workers to the central run's exact environment args."
        )
    if normalized_external == 0 and remote_spec:
        raise SystemExit(f"{REMOTE_SPEC_FLAG} requires {EXTERNAL_ENVS_FLAG} to be greater than zero.")
    return cleaned, DistributedOptions(
        external_envs=normalized_external,
        remote_spec=remote_spec,
    )


def _integer_trainer_arg(
    argv: Sequence[str],
    flag: str,
    default: int,
    *,
    minimum: int = 0,
) -> int:
    value: Optional[str] = None
    for index, argument in enumerate(argv):
        if argument == flag:
            if index + 1 >= len(argv):
                raise SystemExit(f"{flag} requires a value.")
            value = argv[index + 1]
            break
        prefix = flag + "="
        if argument.startswith(prefix):
            value = argument[len(prefix) :]
            break
    if value is None:
        return default
    try:
        parsed = int(value)
    except ValueError as exc:
        raise SystemExit(f"{flag} requires a whole number; got {value!r}.") from exc
    if parsed < minimum:
        raise SystemExit(f"{flag} must be at least {minimum}; got {parsed}.")
    return parsed


def _string_trainer_arg(argv: Sequence[str], flag: str) -> Optional[str]:
    for index, argument in enumerate(argv):
        if argument == flag:
            if index + 1 >= len(argv) or argv[index + 1].startswith("--"):
                raise SystemExit(f"{flag} requires a value.")
            return argv[index + 1]
        prefix = flag + "="
        if argument.startswith(prefix):
            value = argument[len(prefix) :]
            if not value:
                raise SystemExit(f"{flag} requires a value.")
            return value
    return None


def training_topology(argv: Sequence[str], options: DistributedOptions) -> Tuple[int, int, Tuple[int, ...]]:
    total_envs = _integer_trainer_arg(argv, "--num-envs", DEFAULT_NUM_ENVS, minimum=1)
    base_port = _integer_trainer_arg(argv, "--base-port", DEFAULT_BASE_PORT, minimum=1)
    if options.external_envs > total_envs:
        raise SystemExit(
            f"{EXTERNAL_ENVS_FLAG}={options.external_envs} exceeds --num-envs={total_envs}."
        )
    first_external = total_envs - options.external_envs
    worker_ids = tuple(range(first_external, total_envs))
    return total_envs, base_port, worker_ids


def external_worker_ports(base_port: int, worker_ids: Sequence[int]) -> Tuple[int, ...]:
    ports = tuple(base_port + int(worker_id) for worker_id in worker_ids)
    if any(port <= 0 or port > 65535 for port in ports):
        raise ValueError("external ML-Agents worker port is outside 1-65535")
    return ports


def unity_environment_args(argv: Sequence[str]) -> Tuple[str, ...]:
    """Return the exact ML-Agents remainder passed to launched Unity environments."""
    marker_index: Optional[int] = None
    for index, argument in enumerate(argv):
        if argument == "--env-args":
            if marker_index is not None:
                raise SystemExit("--env-args may be specified only once.")
            marker_index = index
        elif argument.startswith("--env-args="):
            raise SystemExit(
                "Use --env-args as a separate token so distributed workers can pin its exact remainder."
            )
    if marker_index is None:
        return ()
    return tuple(str(value) for value in argv[marker_index + 1 :])


def _canonical_json(value: Mapping[str, object]) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def _remote_spec_identity(
    *,
    base_port: int,
    worker_ids: Sequence[int],
    run_id: Optional[str],
    unity_args: Sequence[str],
) -> dict:
    return {
        "schema_version": REMOTE_SPEC_SCHEMA_VERSION,
        "base_port": int(base_port),
        "worker_ids": [int(value) for value in worker_ids],
        "run_id": run_id or "",
        "unity_args": [str(value) for value in unity_args],
    }


def write_remote_worker_spec(
    path: str | os.PathLike[str],
    trainer_args: Sequence[str],
    *,
    base_port: int,
    worker_ids: Sequence[int],
) -> Path:
    """Atomically publish the exact remote rollout command-line contract for this trainer launch."""
    if not worker_ids:
        raise ValueError("remote worker spec requires at least one external worker")
    external_worker_ports(base_port, worker_ids)
    if len(set(int(value) for value in worker_ids)) != len(tuple(worker_ids)):
        raise ValueError("remote worker spec contains duplicate worker IDs")

    identity = _remote_spec_identity(
        base_port=base_port,
        worker_ids=worker_ids,
        run_id=_string_trainer_arg(trainer_args, "--run-id"),
        unity_args=unity_environment_args(trainer_args),
    )
    identity_hash = hashlib.sha256(_canonical_json(identity).encode("utf-8")).hexdigest()
    body = {
        **identity,
        "identity_sha256": identity_hash,
    }
    destination = Path(path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = (json.dumps(body, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")
    fd, temp_name = tempfile.mkstemp(
        prefix=destination.name + ".",
        suffix=".tmp",
        dir=str(destination.parent),
    )
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, destination)
    finally:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass
    return destination


def load_remote_worker_spec(path: str | os.PathLike[str]) -> Mapping[str, object]:
    source = Path(path).expanduser().resolve()
    try:
        value = json.loads(source.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"remote worker spec does not exist: {source}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"remote worker spec is invalid JSON: {source}: {exc}") from exc
    if not isinstance(value, dict) or value.get("schema_version") != REMOTE_SPEC_SCHEMA_VERSION:
        raise ValueError("remote worker spec schema is incompatible")

    base_port = value.get("base_port")
    worker_ids = value.get("worker_ids")
    unity_args = value.get("unity_args")
    run_id = value.get("run_id")
    identity_sha256 = value.get("identity_sha256")
    if not isinstance(base_port, int) or isinstance(base_port, bool) or base_port <= 0:
        raise ValueError("remote worker spec base_port must be a positive integer")
    if (
        not isinstance(worker_ids, list)
        or not worker_ids
        or any(not isinstance(item, int) or isinstance(item, bool) or item < 0 for item in worker_ids)
        or len(set(worker_ids)) != len(worker_ids)
    ):
        raise ValueError("remote worker spec worker_ids must be unique non-negative integers")
    external_worker_ports(base_port, worker_ids)
    if not isinstance(unity_args, list) or any(not isinstance(item, str) for item in unity_args):
        raise ValueError("remote worker spec unity_args must be a string list")
    if not isinstance(run_id, str):
        raise ValueError("remote worker spec run_id must be a string")
    if not isinstance(identity_sha256, str) or len(identity_sha256) != 64:
        raise ValueError("remote worker spec identity_sha256 must be a SHA-256 digest")

    identity = _remote_spec_identity(
        base_port=base_port,
        worker_ids=worker_ids,
        run_id=run_id,
        unity_args=unity_args,
    )
    expected = hashlib.sha256(_canonical_json(identity).encode("utf-8")).hexdigest()
    if identity_sha256 != expected:
        raise ValueError("remote worker spec identity hash does not match its contents")
    return value


class _LoopbackRpcCommunicatorMixin:
    """Bind external-worker gRPC endpoints to loopback so SSH forwarding is mandatory."""

    def create_server(self) -> None:
        import grpc
        from concurrent.futures import ThreadPoolExecutor
        from mlagents_envs.communicator_objects.unity_to_external_pb2_grpc import (
            add_UnityToExternalProtoServicer_to_server,
        )
        from mlagents_envs.rpc_communicator import UnityToExternalServicerImplementation
        from mlagents_envs.exception import UnityWorkerInUseException

        self.check_port(self.port)
        try:
            self.server = grpc.server(
                thread_pool=ThreadPoolExecutor(max_workers=10),
                options=(("grpc.so_reuseport", 1),),
            )
            self.unity_to_external = UnityToExternalServicerImplementation()
            add_UnityToExternalProtoServicer_to_server(self.unity_to_external, self.server)
            bound_port = self.server.add_insecure_port("127.0.0.1:" + str(self.port))
            if bound_port != self.port:
                raise RuntimeError(
                    f"ML-Agents external worker could not bind loopback port {self.port}."
                )
            self.server.start()
            self.is_open = True
        except Exception as exc:
            raise UnityWorkerInUseException(self.worker_id) from exc


def _external_environment_type():
    from mlagents_envs.environment import UnityEnvironment
    from mlagents_envs.rpc_communicator import RpcCommunicator

    class LoopbackRpcCommunicator(_LoopbackRpcCommunicatorMixin, RpcCommunicator):
        pass

    class ExternalUnityEnvironment(UnityEnvironment):
        @staticmethod
        def _get_communicator(worker_id, base_port, timeout_wait):
            return LoopbackRpcCommunicator(worker_id, base_port, timeout_wait)

    return ExternalUnityEnvironment


@contextlib.contextmanager
def _suppress_executable_launch():
    """Let UnityEnvironment build its normal protocol state without starting a local player."""
    from mlagents_envs import env_utils

    original = env_utils.launch_executable
    env_utils.launch_executable = lambda *_args, **_kwargs: None
    try:
        yield
    finally:
        env_utils.launch_executable = original


def _create_external_environment(
    *,
    env_path: str,
    worker_id: int,
    seed: int,
    num_areas: int,
    no_graphics: bool,
    no_graphics_monitor: bool,
    base_port: Optional[int],
    env_args: Optional[List[str]],
    side_channels,
    timeout_wait: int,
):
    ExternalUnityEnvironment = _external_environment_type()
    with _suppress_executable_launch():
        return ExternalUnityEnvironment(
            file_name=env_path,
            worker_id=worker_id,
            seed=seed + worker_id,
            num_areas=num_areas,
            no_graphics=no_graphics,
            no_graphics_monitor=no_graphics_monitor,
            base_port=base_port,
            additional_args=env_args,
            side_channels=side_channels,
            log_folder=None,
            timeout_wait=timeout_wait,
        )


def install_external_worker_factory(
    *,
    total_envs: int,
    external_worker_ids: Sequence[int],
) -> Callable:
    """Patch ML-Agents environment creation so selected IDs wait for remote Unity players."""
    import mlagents.trainers
    import mlagents.trainers.learn as learn

    actual = mlagents.trainers.__version__
    if actual != EXPECTED_MLAGENTS_VERSION:
        raise RuntimeError(
            "Distributed Bees training patches ML-Agents environment creation for version "
            f"{EXPECTED_MLAGENTS_VERSION}, but version {actual} is installed."
        )

    normalized = tuple(sorted(set(int(value) for value in external_worker_ids)))
    if any(worker_id < 0 or worker_id >= total_envs for worker_id in normalized):
        raise RuntimeError("External ML-Agents worker IDs are outside the configured environment range.")
    external_set = frozenset(normalized)
    original = learn.create_environment_factory

    def distributed_create_environment_factory(
        env_path,
        no_graphics,
        no_graphics_monitor,
        seed,
        num_areas,
        timeout_wait,
        start_port,
        env_args,
        log_folder,
    ):
        if external_set and not env_path:
            raise RuntimeError(
                "Distributed external workers require --env so remote Unity executables share the "
                "same build as local workers."
            )
        local_factory = original(
            env_path,
            no_graphics,
            no_graphics_monitor,
            seed,
            num_areas,
            timeout_wait,
            start_port,
            env_args,
            log_folder,
        )

        def create_environment(worker_id, side_channels):
            if worker_id not in external_set:
                return local_factory(worker_id, side_channels)
            return _create_external_environment(
                env_path=env_path,
                worker_id=worker_id,
                seed=seed,
                num_areas=num_areas,
                no_graphics=no_graphics,
                no_graphics_monitor=no_graphics_monitor,
                base_port=start_port,
                env_args=env_args,
                side_channels=side_channels,
                timeout_wait=timeout_wait,
            )

        return create_environment

    learn.create_environment_factory = distributed_create_environment_factory
    return original


def restore_external_worker_factory(original: Optional[Callable]) -> None:
    if original is None:
        return
    import mlagents.trainers.learn as learn

    learn.create_environment_factory = original


def describe_topology(base_port: int, total_envs: int, external_worker_ids: Sequence[int]) -> str:
    external = tuple(external_worker_ids)
    local_count = total_envs - len(external)
    if not external:
        return f"local_envs={total_envs} external_envs=0"
    mappings = ", ".join(
        f"worker {worker_id}->127.0.0.1:{base_port + worker_id}"
        for worker_id in external
    )
    return f"local_envs={local_count} external_envs={len(external)} [{mappings}]"
